CREATE DATABASE GENERATION_FARMACIA;
USE GENERATION_FARMACIA;


CREATE TABLE FORMATO(
	ID BIGINT AUTO_INCREMENT,
	TIPO VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE CATEGORIA(
	ID BIGINT AUTO_INCREMENT,
	DESCRICAO VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE TB_FARMACIA (
	ID BIGINT AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    FORMATO_PRODUTO BIGINT NOT NULL,
    VALOR DECIMAL(6,2) NOT NULL,
	CATEGORIA_PRODUTO BIGINT,
    PRIMARY KEY(ID),
    FOREIGN KEY(FORMATO_PRODUTO) REFERENCES FORMATO(ID),
    FOREIGN KEY(CATEGORIA_PRODUTO) REFERENCES CATEGORIA(ID)
);

INSERT FORMATO(TIPO) 
VALUES  ("COMPRIMIDO"),
		("LIQUIDO"),
        ("OUTROS");
        
INSERT CATEGORIA(DESCRICAO) 
VALUES  ("REMEDIO"),
		("ALIMENTO"),
        ("COSMETICOS");
        
INSERT TB_FARMACIA (NOME,FORMATO_PRODUTO,VALOR,CATEGORIA_PRODUTO) 
VALUES  ("COLFLEX",1,29.99,1),
		("OMEGA 2",1,49.99,1),
        ("DORFLEX",1,39.99,1),
        ("DESODORANTE",3,39.99,3),
        ("SABONETE EM BARRA",3,15.99,3),
        ("BARRA DE CHOCOLATE",3,10.99,2);
        
SELECT * FROM TB_FARMACIA
WHERE VALOR > 20;

SELECT * FROM TB_FARMACIA
WHERE VALOR BETWEEN 20 AND 60; 

-- LIKE
SELECT * FROM TB_FARMACIA
WHERE NOME LIKE "D%";

-- INNER JOIN
SELECT FA.NOME, FO.TIPO, CA.DESCRICAO
			FROM TB_FARMACIA AS FA
			INNER JOIN FORMATO AS FO 
			ON FO.ID = FA.FORMATO_PRODUTO
            INNER JOIN CATEGORIA AS CA
            ON CA.ID = FA.CATEGORIA_PRODUTO;           

-- SELECT ESPECIFICO
SELECT FA.NOME, FA.VALOR, FO.TIPO, CA.DESCRICAO 

			FROM TB_FARMACIA AS FA
			INNER JOIN FORMATO AS FO 
			ON FO.ID = FA.FORMATO_PRODUTO
            INNER JOIN CATEGORIA AS CA
            ON CA.ID = FA.CATEGORIA_PRODUTO
			WHERE FA.VALOR > 20;
